### ISSUE TITLE
Maybe rename to TensorBoard.jl?

### ISSUE THREAD

**Issue by juliohm** [oxinabox/UniversalTensorBoard.jl#1]
Thanks for the initiative @oxinabox! It was great to chat on slack, and now see the project getting started :)

Just wondering what was your rationale to call the package "Universal"?

**Comment by oxinabox** [comment]
Because traditionally logging with tensor board is only done for TensorFlow models.

**Comment by juliohm** [comment]
Got it, I find TensorBoard.jl cooler :) Thanks for the initiative!
